### ISSUE TITLE
Clarity on categories in LF Edge landscape

### ISSUE THREAD

**Issue by geseiler** [lf-edge/lfedge-landscape#53]
It would be helpful if there was some kind of definition for the categories.
For example what is the difference/definition of a platform versus infrastructure?
Both have a Virtualization subcategory.
Also not clear if Virtualization is meant loosely, i.e. included containers? Or just VMs.

We are struggling on where to place StarlingX for example, as it fits in multiple categories. As it is a component of an Akraino blueprint, and an independent project, should it be in the same category as Akraino.

**Comment by wesreisz** [comment]
@geseiler You're completely right. Just just pushed the categories to the Readme. We'll get them added to the Glossary longterm. On the virtualization category, we moved it and it didn't get cleaned up. Virtualization mean VMs, containers, unikernels, etc.... it means a virtualized resource.
